name: mabile_bank_group_mmmx
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.0.0
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.3
  intl: ^0.17.0
  intl_phone_number_input: ^0.7.2
  mask_text_input_formatter: ^2.4.0
  flutter_otp_text_field: ^1.1.1
  dependencies:
  lottie: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  fonts:
    - family: Manrope
      fonts:
        - asset: fonts/google_manrope/manrope.ttf


  assets:
    - assets/images/
    - assets/res/
